version: '3.9'

services:
  backend:
    build: ./backend
    container_name: tracker_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tracker_redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
